{
    'name': 'EMI Application',
    'version': '19.0.1.0.0',
    'summary': 'Online EMI application, KYC intake and the approval workflow',
    'description': """
EMI Application
================
The core transactional module of the EMI Platform. Ties together a
customer, a marketplace product (emi_marketplace), a finance company and
tenure plan (emi_finance) into a single application record.

Workflow
--------
draft -> submitted -> kyc_review -> pending_finance_approval
       -> approved -> disbursed -> active -> closed
                    \\-> rejected                    \\-> defaulted

* KYC intake with document uploads
* Down payment selection against a product's configured options, with the
  customer allowed to pay more than the selected minimum
* An estimated EMI preview computed from the active interest rate (flat or
  reducing balance) at submission time; the authoritative amortization
  schedule and accounting entries are generated by emi_accounting on
  disbursement
* Two-stage approval: marketplace EMI Officer reviews KYC first, the
  finance company's own reviewer (scoped to their own company) gives
  final credit approval
""",
    'category': 'Accounting/Finance',
    'author': 'EMI Platform',
    'license': 'LGPL-3',
    'depends': ['emi_finance', 'emi_marketplace', 'portal', 'mail'],
    'data': [
        'security/application_security.xml',
        'security/ir.model.access.csv',
        'data/sequence_data.xml',
        'views/kyc_views.xml',
        'views/application_views.xml',
        'views/menu_views.xml',
    ],
    'installable': True,
    'application': True,
}
